### ISSUE TITLE
ICE Failed

### ISSUE THREAD

**Issue by gkunwar** [mojolingo/talking-stick-demo#13] opened 2016-12-09 06:05 UTC
On Firefox I can am not able to see the remote video when I connected from different notwork.

Found following error:

> ICE failed, see about:webrtc for more details

Anyone help me.
Is this due to the SSL certificate or any other reason

I also tested on your demo site, same error appearing.

**Comment by bklang** [comment] 2016-12-09 13:45
Closing; duplicate of mojolingo/talking_stick#34

**Closed as completed by bklang** 2016-12-09 13:45 UTC
